apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  namespace: roboshop
  # deplyment labels
  labels:
    component: catalogue
    project: roboshop
    tier: app
spec:
  replica: 1
  # these are the labels replica set use to create pod replicas, this should match pod lables
  selector:
    matchLabels:
      component: catalogue
      project: roboshop
      tier: app
  # this is pod definition
  template:
    metadata:
      labels:
        component: catalogue
        project: roboshop
        tier: app
    spec: 
      containers:
      - name: catalogue
        image: "{{ .Values.deployment.imageURL}}:{{ .Values.deployment.imageVersion }}"
        resources:
          requests:
            cpu: "50m"
            memory: "128Mi"
          limits:
            cpu: "100m"
            memory: "256Mi"
        envFrom:
        - coonfigMapRef:
            name: catalogue
  